docker run \
 -d \
 --name newrelic-infra \
 --network=host \
 --cap-add=SYS_PTRACE \
 --privileged \
 --pid=host \
 -v "/:/host:ro" \
 -v "/var/run/docker.sock:/var/run/docker.sock" \
 -e  NRIA_LICENSE_KEY=1aec7003ab2306539cbdc7b5bb8353dfFFFFNRAL \
 newrelic/infrastructure:latest