name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{env.HEROKU_API_KEY}}
          heroku_app_name: ${{env.HEROKUAAPP_STAGING"}} #Must be unique in Heroku
          heroku_email: ${{env.EMAIL}}
          usedocker: true
          # healthcheck: "https://.herokuapp.com/health"